// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbPS76eI2FjgU74xPdRAW8mYDQFJdUTM0',
    appId: '1:1061630815268:web:75e137b901cbba9c50fcb1',
    messagingSenderId: '1061630815268',
    projectId: 'todo-6fa67',
    authDomain: 'todo-6fa67.firebaseapp.com',
    storageBucket: 'todo-6fa67.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvURHhj35Hxi7-pYVldJU-mVE0UNwdJRk',
    appId: '1:1061630815268:android:4b9055e26f09a66850fcb1',
    messagingSenderId: '1061630815268',
    projectId: 'todo-6fa67',
    storageBucket: 'todo-6fa67.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtlukbcYS7yuOgDLvs6ctONz9ozsDulTk',
    appId: '1:1061630815268:ios:41b5613d1dfe3aff50fcb1',
    messagingSenderId: '1061630815268',
    projectId: 'todo-6fa67',
    storageBucket: 'todo-6fa67.appspot.com',
    iosClientId: '1061630815268-plvph2q7pekl11nchos998h8pslhivn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todofirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtlukbcYS7yuOgDLvs6ctONz9ozsDulTk',
    appId: '1:1061630815268:ios:41b5613d1dfe3aff50fcb1',
    messagingSenderId: '1061630815268',
    projectId: 'todo-6fa67',
    storageBucket: 'todo-6fa67.appspot.com',
    iosClientId: '1061630815268-plvph2q7pekl11nchos998h8pslhivn2.apps.googleusercontent.com',
    iosBundleId: 'com.example.todofirebase',
  );
}
