// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkCci4AGDOErNFRgfUV2NGuWjsBytfxYg',
    appId: '1:692745768515:web:32dac70227f7ac99630ef6',
    messagingSenderId: '692745768515',
    projectId: 'instagram-clone-37e3b',
    authDomain: 'instagram-clone-37e3b.firebaseapp.com',
    storageBucket: 'instagram-clone-37e3b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuLGBCpUGShaS3dJ7yShvZCZ5LVLZPunw',
    appId: '1:692745768515:android:b70a1420ade595e2630ef6',
    messagingSenderId: '692745768515',
    projectId: 'instagram-clone-37e3b',
    storageBucket: 'instagram-clone-37e3b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvs3fthemhVd6g6bG1I1P2y-5Cvx8jcnY',
    appId: '1:692745768515:ios:18496d9e46d58def630ef6',
    messagingSenderId: '692745768515',
    projectId: 'instagram-clone-37e3b',
    storageBucket: 'instagram-clone-37e3b.appspot.com',
    iosClientId: '692745768515-50lv9cl68bidit03qt0f1gk737gs03ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullstackInstagramClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvs3fthemhVd6g6bG1I1P2y-5Cvx8jcnY',
    appId: '1:692745768515:ios:18496d9e46d58def630ef6',
    messagingSenderId: '692745768515',
    projectId: 'instagram-clone-37e3b',
    storageBucket: 'instagram-clone-37e3b.appspot.com',
    iosClientId: '692745768515-50lv9cl68bidit03qt0f1gk737gs03ru.apps.googleusercontent.com',
    iosBundleId: 'com.example.fullstackInstagramClone',
  );
}
