// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBe1Ty6c0kQ1F7Idr01AaV1YvUyAknKGEs',
    appId: '1:1012744069591:web:dca9775abb15a65dbe2b92',
    messagingSenderId: '1012744069591',
    projectId: 'chat-gpt-clone-6bb39',
    authDomain: 'chat-gpt-clone-6bb39.firebaseapp.com',
    storageBucket: 'chat-gpt-clone-6bb39.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIeNChx53NouXzFwZhHzAewZBsjRHPbWI',
    appId: '1:1012744069591:android:2c76a31330fb5689be2b92',
    messagingSenderId: '1012744069591',
    projectId: 'chat-gpt-clone-6bb39',
    storageBucket: 'chat-gpt-clone-6bb39.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBm8ZXk0oCpRyYgJju4w7RPXds3YvbU0SM',
    appId: '1:1012744069591:ios:56a2a0f454e8233bbe2b92',
    messagingSenderId: '1012744069591',
    projectId: 'chat-gpt-clone-6bb39',
    storageBucket: 'chat-gpt-clone-6bb39.appspot.com',
    iosBundleId: 'com.example.chatGptClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBm8ZXk0oCpRyYgJju4w7RPXds3YvbU0SM',
    appId: '1:1012744069591:ios:ff980731223102e6be2b92',
    messagingSenderId: '1012744069591',
    projectId: 'chat-gpt-clone-6bb39',
    storageBucket: 'chat-gpt-clone-6bb39.appspot.com',
    iosBundleId: 'com.example.chatGptClone.RunnerTests',
  );
}
