// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5UFanDkUFWrZdLe2WGRHKCgS-YVqwbfk',
    appId: '1:760555267133:web:d56ab05ba93d23a55db654',
    messagingSenderId: '760555267133',
    projectId: 'cattle-herding-4ae31',
    authDomain: 'cattle-herding-4ae31.firebaseapp.com',
    databaseURL: 'https://cattle-herding-4ae31-default-rtdb.firebaseio.com',
    storageBucket: 'cattle-herding-4ae31.appspot.com',
    measurementId: 'G-JTM6L696B1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCqpOqWlunC3tJ8GOGB91pogaddPzZIps',
    appId: '1:760555267133:android:6b140520e9ec83ef5db654',
    messagingSenderId: '760555267133',
    projectId: 'cattle-herding-4ae31',
    databaseURL: 'https://cattle-herding-4ae31-default-rtdb.firebaseio.com',
    storageBucket: 'cattle-herding-4ae31.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCl2EiYsJkXet6X0A2nA7CXbpZfHo9EvpI',
    appId: '1:760555267133:ios:cb70efdc902768695db654',
    messagingSenderId: '760555267133',
    projectId: 'cattle-herding-4ae31',
    databaseURL: 'https://cattle-herding-4ae31-default-rtdb.firebaseio.com',
    storageBucket: 'cattle-herding-4ae31.appspot.com',
    iosClientId: '760555267133-033ljq0p7q4bn3216a1msmef1c7bud37.apps.googleusercontent.com',
    iosBundleId: 'com.example.cattleHerdingWithGeofencing',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCl2EiYsJkXet6X0A2nA7CXbpZfHo9EvpI',
    appId: '1:760555267133:ios:b34649c8c7268ff45db654',
    messagingSenderId: '760555267133',
    projectId: 'cattle-herding-4ae31',
    databaseURL: 'https://cattle-herding-4ae31-default-rtdb.firebaseio.com',
    storageBucket: 'cattle-herding-4ae31.appspot.com',
    iosClientId: '760555267133-66skf5m5inf0edop7nn79qr20mo3oh6o.apps.googleusercontent.com',
    iosBundleId: 'com.example.cattleHerdingWithGeofencing.RunnerTests',
  );
}
